# Generated by Django 6.0.1 on 2026-01-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
